# Generated by Django 5.0.6 on 2024-09-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_checkout_session_id', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('has_access', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='The custom user who initiated the checkout.', on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
