# Generated by Django 5.0.6 on 2024-09-09 14:07

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3,}$', 'The name must consist of at least 3 letters.', flags=re.RegexFlag['IGNORECASE'])], verbose_name='First name')),
                ('surname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3,}$', 'Surname must consist of at least 3 letters.', flags=re.RegexFlag['IGNORECASE'])], verbose_name='Last name')),
                ('phone', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Phone number must consist of at least 9 digits.', flags=re.RegexFlag['IGNORECASE'])], verbose_name='Phone')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date joined')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='Company name')),
                ('bcc_1', models.EmailField(blank=True, max_length=50, null=True, verbose_name='BCC address no 1')),
                ('bcc_2', models.EmailField(blank=True, max_length=50, null=True, verbose_name='BCC address no 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSmtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=3)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tls', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
