# Generated by Django 5.0.6 on 2024-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription expiration'),
        ),
    ]
