# Generated by Django 5.0.6 on 2024-09-09 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Strona internetowa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailFollowup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('initial_message', models.BooleanField(default=False, verbose_name='First message')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('date_to_send', models.DateTimeField(blank=True, null=True, verbose_name='Data wysłania')),
                ('original_text', models.TextField(verbose_name='Original message')),
                ('improved_text', models.TextField(blank=True, null=True, verbose_name='Improved message')),
                ('status', models.CharField(choices=[('TO SEND', 'To Send'), ('SENT', 'Sent')], max_length=10, verbose_name='Status')),
                ('bcc_1', models.EmailField(blank=True, max_length=50, null=True, verbose_name='BCC address no 1')),
                ('bcc_2', models.EmailField(blank=True, max_length=50, null=True, verbose_name='BCC address no 2')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_email_followups', to='mail.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_to_send', models.DateTimeField(verbose_name='Data wysłania')),
                ('improved_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO SEND', 'To Send'), ('SENT', 'Sent')], max_length=10, verbose_name='Status')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.emailfollowup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recipients', to='mail.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], max_length=2, verbose_name='Language')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('STOPPED', 'Stopped')], max_length=10, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_pipelines', to='mail.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pipelines', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_pipelines', to='mail.recipient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailfollowup',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_email_followups', to='mail.recipient'),
        ),
    ]
