# Generated by Django 5.0.6 on 2024-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
